export const shopActionTypes = {
   COLLECTIONS_FETCHING_START: "COLLECTIONS_FETCHING_START",
   COLLECTIONS_FETCHING_SUCCESSFUL: "COLLECTIONS_FETCHING_SUCCESSFUL",
   COLLECTIONS_FETCHING_FAILURE: "COLLECTIONS_FETCHING_FAILURE",
}