const cartTypes = {
   TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
   ADD_ITEM: 'ADD_ITEM',
   REMOVE_ITEM: 'REMOVE_ITEM',
   CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
   CLEAR_CART_ON_SIGN_OUT: 'CLEAR_CART_ON_SIGN_OUT',
}

export default cartTypes